INSERT INTO auteurs (nom,prenom) VALUES ('Venter','J. Craig');
INSERT INTO auteurs (nom,prenom) VALUES ('Stiegler','Patrick');
INSERT INTO auteurs (nom,prenom) VALUES ('Gish','W.');
INSERT INTO auteurs (nom,prenom) VALUES ('Zuker','Michael');
INSERT INTO auteurs (nom,prenom) VALUES ('Amara','J.');
INSERT INTO auteurs (nom,prenom) VALUES ('Robinzon','B.');
INSERT INTO auteurs (nom,prenom) VALUES ('Lindquist','Susan L.');
INSERT INTO auteurs (nom,prenom) VALUES ('Needleman','Saul B.');
INSERT INTO auteurs (nom,prenom) VALUES ('Schbath','Sophie');
INSERT INTO auteurs (nom,prenom) VALUES ('Davenas','E.');
INSERT INTO auteurs (nom,prenom) VALUES ('Fox','George E.');
INSERT INTO auteurs (nom,prenom) VALUES ('Kececioglu','J. D.');
INSERT INTO auteurs (nom,prenom) VALUES ('Sainte-Laudy','J.');
INSERT INTO auteurs (nom,prenom) VALUES ('Zerbino','Daniel R.');
INSERT INTO auteurs (nom,prenom) VALUES ('Altschul','S. F.');
INSERT INTO auteurs (nom,prenom) VALUES ('Wilbur','W. J.');
INSERT INTO auteurs (nom,prenom) VALUES ('Miller','W.');
INSERT INTO auteurs (nom,prenom) VALUES ('Franklin','Rosalind E.');
INSERT INTO auteurs (nom,prenom) VALUES ('Oberbaum','M.');
INSERT INTO auteurs (nom,prenom) VALUES ('Chan','Patricia P.');
INSERT INTO auteurs (nom,prenom) VALUES ('Schulz','Marcel H.');
INSERT INTO auteurs (nom,prenom) VALUES ('McClintock','Barbara');
INSERT INTO auteurs (nom,prenom) VALUES ('Krishnan','Rajaraman');
INSERT INTO auteurs (nom,prenom) VALUES ('Lowe','Todd M.');
INSERT INTO auteurs (nom,prenom) VALUES ('Miadonnai','A.');
INSERT INTO auteurs (nom,prenom) VALUES ('Waterman','M. S.');
INSERT INTO auteurs (nom,prenom) VALUES ('Creighton','Harriet B.');
INSERT INTO auteurs (nom,prenom) VALUES ('Sadler','J. R.');
INSERT INTO auteurs (nom,prenom) VALUES ('Birney','Ewan');
INSERT INTO auteurs (nom,prenom) VALUES ('Margulis','Lynn');
INSERT INTO auteurs (nom,prenom) VALUES ('Beauvais','F.');
INSERT INTO auteurs (nom,prenom) VALUES ('Rowley','Janet D.');
INSERT INTO auteurs (nom,prenom) VALUES ('Fichant','Gwennaele A.');
INSERT INTO auteurs (nom,prenom) VALUES ('Wunsch','Christian D.');
INSERT INTO auteurs (nom,prenom) VALUES ('Fortner','P.');
INSERT INTO auteurs (nom,prenom) VALUES ('Poitevin','B.');
INSERT INTO auteurs (nom,prenom) VALUES ('Nicklen','S.');
INSERT INTO auteurs (nom,prenom) VALUES ('Smith','Hamilton O.');
INSERT INTO auteurs (nom,prenom) VALUES ('Turing','Alan');
INSERT INTO auteurs (nom,prenom) VALUES ('Pomeranz','B.');
INSERT INTO auteurs (nom,prenom) VALUES ('Vingron','Martin');
INSERT INTO auteurs (nom,prenom) VALUES ('Dayhoff','Margaret Oakley');
INSERT INTO auteurs (nom,prenom) VALUES ('Sutton','Granger G.');
INSERT INTO auteurs (nom,prenom) VALUES ('Crick','Francis');
INSERT INTO auteurs (nom,prenom) VALUES ('Smith','T. F.');
INSERT INTO auteurs (nom,prenom) VALUES ('Myers','Eugene W.');
INSERT INTO auteurs (nom,prenom) VALUES ('Burks','C.');
INSERT INTO auteurs (nom,prenom) VALUES ('Lin','Brian Y.');
INSERT INTO auteurs (nom,prenom) VALUES ('Belon','P.');
INSERT INTO auteurs (nom,prenom) VALUES ('Coulson','A. R.');
INSERT INTO auteurs (nom,prenom) VALUES ('Eck','R. V.');
INSERT INTO auteurs (nom,prenom) VALUES ('Watson','James Dewey');
INSERT INTO auteurs (nom,prenom) VALUES ('Adams','Mark D.');
INSERT INTO auteurs (nom,prenom) VALUES ('Woese','Carl R.');
INSERT INTO auteurs (nom,prenom) VALUES ('Sanger','F.');
INSERT INTO auteurs (nom,prenom) VALUES ('Tedeschi','A.');
INSERT INTO auteurs (nom,prenom) VALUES ('Mak','Allysia J.');
INSERT INTO auteurs (nom,prenom) VALUES ('Benveniste','J.');
INSERT INTO auteurs (nom,prenom) VALUES ('Margoliash','E.');
INSERT INTO auteurs (nom,prenom) VALUES ('Fitch','W. M.');
INSERT INTO auteurs (nom,prenom) VALUES ('Lipman','David J.');
