INSERT INTO journaux (issn,nom_journal,abreviation,editeur) VALUES ('0028-0836','Nature','Nature','Nature Publishing Group');
INSERT INTO journaux (issn,nom_journal,abreviation,editeur) VALUES ('0962-8436','Philosophical Transactions of the Royal Society of London B: Biological Sciences','Phil. Trans. R. Soc. Lon. B','Royal Society');
INSERT INTO journaux (issn,nom_journal,abreviation,editeur) VALUES ('1066-5277','Journal of Computational Biology','J. Comput. Biol.','Mary Ann Liebert');
INSERT INTO journaux (issn,nom_journal,abreviation,editeur) VALUES ('0305-1048','Nucleic Acids Research','Nucl. Acids Res.','Oxford University Press');
INSERT INTO journaux (issn,nom_journal,abreviation,editeur) VALUES ('2059-7983','Acta Crystallographica','Acta Cryst.','International Union of Crystallography');
INSERT INTO journaux (issn,nom_journal,abreviation,editeur) VALUES ('0010-4825','Computers in Biology and Medicine','Comp. Biol. Med.','Elsevier');
INSERT INTO journaux (issn,nom_journal,abreviation,editeur) VALUES ('0036-8075','Science','Science','American Association for the Advancement of Science');
INSERT INTO journaux (issn,nom_journal,abreviation,editeur) VALUES ('0022-2836','Journal of Molecular Biology','J. Mol. Biol.','Academic Press');
INSERT INTO journaux (issn,nom_journal,abreviation,editeur) VALUES ('1367-4803','Bioinformatics','Bioinformatics','Oxford University Press');
INSERT INTO journaux (issn,nom_journal,abreviation,editeur) VALUES ('0016-6731','Genetics','Genetics','Genetics Society of America');
INSERT INTO journaux (issn,nom_journal,abreviation,editeur) VALUES ('0027-8424','Proceedings of the National Academy of Sciences of the United States of America','Proc. Natl. Acad. Sci. USA','National Academy of Sciences');
INSERT INTO journaux (issn,nom_journal,abreviation,editeur) VALUES ('0002-9297','American Journal of Human Genetics','Amer. J. Hum. Genet.','American Society of Human Genetics');
